### ISSUE TITLE
Organisation Scrum/Agile

### ISSUE THREAD

**Issue by GuillaumeDua** [kannako/Nereala-#1]
Pourquoi ne pas faire 3 piles de tickets ?
. todo
. in progress
. done

**Comment by kannako** [comment]
Je rajoute en cours alors j'ai mis là première en mode balance d'idée en vrac ( et puis pour test un peu Git hub faut dire)

**Comment by kannako** [comment]
Par ce que sinon c'est là même chose mais en franchouillard quoi 
.todo ( va falloir si mettre )
.in progress ( On y travaille)
.Done ( Bon ÇA déjà c'est fait)

Je trouvais ça marrant. Sinon comme je connais pas vraiment le fonctionnement dit moi les trucs a changer.

**Comment by GuillaumeDua** [comment]
L'idee c'est que TOUT les tickets vont forcement passer de "todo" a "in
progress" puis finalement "Done".
Sachant que l'on peut rajouter un "Won't do" pour mettre les idees que l'on
choisit de ne pas realiser.
Considere la vie d'un ticket comme un flux :)

Guillaume Dua
Concepteur, developpeur, architecte, code-reviewer et formateur C++
[-- Guss=) --]

Ce message et toutes les pièces jointes sont confidentiels et établis à
l'intention exclusive de ses destinataires.  Si vous recevez ce message par
erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur.
Toute utilisation de ce message non conforme à sa destination, toute
diffusion ou toute publication, totale ou partielle, est interdite, sauf
autorisation expresse.

This message contains confidential information and is intended only for the
individual or entity named. If you are not the named addressee you should
not disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail and any attachments from your systems.

Please think of the environment before you print this e-mail.

**Comment by kannako** [comment]
J'ai rajouté entre parenthèse les trois colonnes -Todo -In progress - Done
